// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIsWpGlvYb0dFTvl8A8seEgixgJT9HkWc',
    appId: '1:1069208287796:web:ba4aeaccf2561a6b5be861',
    messagingSenderId: '1069208287796',
    projectId: 'flutter-chat-app-ee340',
    authDomain: 'flutter-chat-app-ee340.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ee340.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUddtEpV6Eh3ODRlYwAtEEcY48XuKrDjU',
    appId: '1:1069208287796:android:f8edc1d77a1cd3505be861',
    messagingSenderId: '1069208287796',
    projectId: 'flutter-chat-app-ee340',
    storageBucket: 'flutter-chat-app-ee340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhbmUV6SCt-nLCKrqDEAhMJwqtWt1Xk5w',
    appId: '1:1069208287796:ios:f7f296394f22d45a5be861',
    messagingSenderId: '1069208287796',
    projectId: 'flutter-chat-app-ee340',
    storageBucket: 'flutter-chat-app-ee340.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhbmUV6SCt-nLCKrqDEAhMJwqtWt1Xk5w',
    appId: '1:1069208287796:ios:f7f296394f22d45a5be861',
    messagingSenderId: '1069208287796',
    projectId: 'flutter-chat-app-ee340',
    storageBucket: 'flutter-chat-app-ee340.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIsWpGlvYb0dFTvl8A8seEgixgJT9HkWc',
    appId: '1:1069208287796:web:16eae077fe0a037b5be861',
    messagingSenderId: '1069208287796',
    projectId: 'flutter-chat-app-ee340',
    authDomain: 'flutter-chat-app-ee340.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ee340.firebasestorage.app',
  );

}